export default {
  MEDIUM_SIZE_RESPONSIVE: 1199,
  SMALL_SIZE_RESPONSIVE: 699,

  CONCAT_OPERATION: "concat",
  DIFF_OPERATION: "diff",
  SYM_DIFF_OPERATION: "sym-diff",
  INTERSECT_OPERATION: "intersect",
  UNION_OPERATION: "union",

  JSON_FILE_FORMAT: "json",
  CSV_FILE_FORMAT: "csv",

  GRID_COLUMNS_AMOUNT: 3,
  ITEM_TRANSITION_TIME: 0.25,
  ARRAY_GRID_GAP: 14,
};
